#!/usr/bin/env bash
# =============================================================================
# Daily CI Triage Script
# =============================================================================
# Part of the loop engineering automation system. Analyzes CI status, open
# issues, and recent commits to produce a categorized triage report.
#
# Usage: bash scripts/daily-triage.sh [--output-dir learnings]
# =============================================================================

set -euo pipefail

OUTPUT_DIR="${1:-learnings}"
mkdir -p "$OUTPUT_DIR"

TODAY=$(date +%Y-%m-%d)
REPORT="$OUTPUT_DIR/triage-$TODAY.md"

echo "# Daily Triage Report: $TODAY" > "$REPORT"
echo "" >> "$REPORT"
echo "_Generated by daily-triage.sh_" >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 1: Recent commits ---
echo "## Recent Commits (last 24h)" >> "$REPORT"
echo "" >> "$REPORT"
if git log --since="24 hours ago" --oneline --no-decorate 2>/dev/null | head -20; then
    git log --since="24 hours ago" --oneline --no-decorate 2>/dev/null | head -20 >> "$REPORT"
else
    echo "(no commits in last 24h or not a git repository)" >> "$REPORT"
fi
echo "" >> "$REPORT"

# --- Section 2: Branch status ---
echo "## Branch Status" >> "$REPORT"
echo "" >> "$REPORT"
echo "- **main:** $(git rev-parse --short main 2>/dev/null || echo 'N/A')" >> "$REPORT"
echo "- **develop:** $(git rev-parse --short develop 2>/dev/null || echo 'N/A')" >> "$REPORT"
echo "- **active branches:**" >> "$REPORT"
git branch -r --sort=-committerdate 2>/dev/null | head -10 | sed 's/^/  - /' >> "$REPORT" || echo "  (none)" >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 3: Worktree status ---
echo "## Active Worktrees" >> "$REPORT"
echo "" >> "$REPORT"
if git worktree list 2>/dev/null; then
    git worktree list 2>/dev/null >> "$REPORT"
else
    echo "(none)" >> "$REPORT"
fi
echo "" >> "$REPORT"

# --- Section 4: Open issues (if gh CLI is available) ---
echo "## Open Issues (up to 10)" >> "$REPORT"
echo "" >> "$REPORT"
if command -v gh &>/dev/null; then
    if gh issue list --limit 10 --json number,title,labels,createdAt 2>/dev/null; then
        gh issue list --limit 10 --json number,title,labels,createdAt 2>/dev/null | \
            python3 -c "
import sys, json
try:
    issues = json.load(sys.stdin)
    for i in issues:
        labels = ','.join(l['name'] for l in i.get('labels', []))
        print(f\"  - #{i['number']} {i['title']} [{labels}] ({i['createdAt'][:10]})\")
except: pass
" >> "$REPORT
    else
        echo "(gh CLI not authenticated or no issues)" >> "$REPORT"
    fi
else
    echo "(gh CLI not installed)" >> "$REPORT"
fi
echo "" >> "$REPORT"

# --- Section 5: Categorization ---
echo "## Categorization" >> "$REPORT"
echo "" >> "$REPORT"
echo "### 🔴 Critical" >> "$REPORT"
echo "- _(none identified — automated triage requires human review for critical items)_" >> "$REPORT"
echo "" >> "$REPORT"
echo "### 🟡 Needs Attention" >> "$REPORT"
echo "- _(add items here based on CI failures or stale branches)_" >> "$REPORT"
echo "" >> "$REPORT"
echo "### ℹ️ Info" >> "$REPORT"
echo "- Triage report generated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 6: Recommendations ---
echo "## Recommendations" >> "$REPORT"
echo "" >> "$REPORT"
echo "- Review the triage report and update Critical/Needs-Attention sections" >> "$REPORT"
echo "- Run \`scripts/validate-skills.py\` to check skill health" >> "$REPORT"
echo "- Check CI status: \`gh run list --limit 5\`" >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 7: State file update ---
STATE_FILE="STATE.md"
INBOX_DIR="inbox"
mkdir -p "$INBOX_DIR" "$INBOX_DIR/archive"

if [ -f "$STATE_FILE" ]; then
    # Update existing state file
    sed -i "s/Last updated:.*/Last updated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')/" "$STATE_FILE"
    sed -i "s/Last triage run:.*/Last triage run: $TODAY/" "$STATE_FILE"
    echo "✅ STATE.md updated"
else
    # Create initial state file
    cat > "$STATE_FILE" << STATEEOF
# Loop State

**Last updated:** $(date -u '+%Y-%m-%dT%H:%M:%SZ')
**Last triage run:** $TODAY
**Open items:** 0

| Item | Status | Source | Since |
|------|--------|--------|-------|
| _(no open items — initial triage run)_ | | | |
STATEEOF
    echo "✅ STATE.md created"
fi

echo "✅ Triage report written to $REPORT"
